### ISSUE TITLE
Make all the tests pass

### ISSUE THREAD

**Issue by StanleyMasinde** [opensource254/covidapi#91]
I have realised that all builds/tets on Travis ci are failing probably due to a misconfiguration.
I would suggest this,
1. We move back to GH actions
2. Use Sqlite3 for testing DB

What do you guys think?

**Comment by miami78** [comment]
Thats a pretty good idea @StanleyMasinde ,im in!

**Comment by BILLthebuilder** [comment]
It's a good idea, but I don't know if sqlite3 has support for geometry types

**Comment by StanleyMasinde** [comment]
@BILLthebuilder we can use this https://www.npmjs.com/package/spatialite

**Comment by StanleyMasinde** [comment]
> Thats a pretty good idea @StanleyMasinde ,im in!

Awesome

**Comment by BILLthebuilder** [comment]
> @BILLthebuilder we can use this https://www.npmjs.com/package/spatialite

Awesome, you guys can get started on it

**Comment by StanleyMasinde** [comment]
> > @BILLthebuilder we can use this https://www.npmjs.com/package/spatialite
> 
> Awesome, you guys can get started on it

I was hoping it would be you and Wilcox because you did most of the database part. We are here for support

**Comment by BILLthebuilder** [comment]
> > > @BILLthebuilder we can use this https://www.npmjs.com/package/spatialite
> > 
> > 
> > Awesome, you guys can get started on it
> 
> I was hoping it would be you and Wilcox because you did most of the database part. We are here for support

Okay, I'll see if I can steal some time

**Comment by StanleyMasinde** [comment]
Awesome
